#! /usr/bin/env bash

libtoolize --copy --force && \
        aclocal -I macros $ACLOCAL_FLAGS && \
        autoheader && \
        automake --include-deps --add-missing --foreign && \
        autoconf