#! /usr/bin/env bash
aclocal \
        && automake --gnu --add-missing \
        && autoconf

libtoolize --copy --force && \
        aclocal -I macros $ACLOCAL_FLAGS && \
        autoheader && \
        automake --include-deps --add-missing --foreign && \
        autoconf
